### ISSUE TITLE
A - Elliptic Arc Render Issue

### ISSUE THREAD

**Issue by VICTORVICKIE** [shashi278/svg-anim-kivy#1]
### Elliptic Arc does not render. 
[Gist for the example](https://gist.github.com/VICTORVICKIE/986a4f1ea11afd26a76bf32fd3f15eb4)

**Kivg** :

![image](https://user-images.githubusercontent.com/45727291/123575453-69603380-d7ef-11eb-968c-69af838c0080.png)

**SvgPathEditor** :

![image](https://user-images.githubusercontent.com/45727291/123575492-8137b780-d7ef-11eb-91b5-a563281ab1df.png)

**Comment by shashi278** [comment]
Hi @VICTORVICKIE, thanks for pointing it out. Honestly, arcs are kinda pain to work with but, fortunately, there are workarounds. I've added some useful links in the Readme that one can use to modify a few svg files in order to work with this library.
Kindly read here: https://github.com/shashi278/svg-anim-kivy#useful-links and let me know if that's useful.
