### ISSUE TITLE
Some SVG Files Not Rendered At ALL

### ISSUE THREAD

**Issue by qodzero** [shashi278/svg-anim-kivy#2]
Hi there, thanks for this life-saver, I am however having a rather puzzling issue, when I try this package with SVGs in the demo folder, everything works great but as soon as I use my own SVG files, nothing is rendered, as in there is no error that comes up but in the UI there is literally nothing being rendered. To Test, please use [these svg files](https://github.com/shashi278/svg-anim-kivy/files/7074733/img.zip)

**Comment by shashi278** [comment]
Hey @qodzero, thanks for bringing this out and waiting so long for the response. Turned out there is some issue parsing the svg size if they're not `int`. It'll be fixed soon.
Other than that, you'd also need to modify your svgs a bit, like setting colors as `fill` attribute to `path` tags for them to be parsable, and changing arcs to cubic bezier.

Here, after modification.
![Screenshot from 2021-09-03 21-35-36](https://user-images.githubusercontent.com/37111736/132038660-2569b5f9-70eb-4a48-8d2e-4c8108b20f14.png)

**Comment by qodzero** [comment]
Would you have an idea of how I can do the modifications to the svgs, I
tried your link but can't understand what to do after pasting the svg data
in the input box, there is no download button, just done flutter code

**Comment by shashi278** [comment]
If you see an `A` or `a` which means arcs in any path, copy that entire path string and paste it on the website. Don't forget to enter dimensions as well. On submit, it'll give you a new path (ignore the flutter part), copy and paste this entire path in place of the previous path. Also, add `Z` at the end of the new path if it's not already there. Other than this, you may also need to add a `fill="#somehexcolor"` inside the `<svg>` tag like `< svg fill="#858474" ....>` for it to detect color.

**Comment by qodzero** [comment]
Hey again sorry to keep bothering you but, it still doesn't work, my
observations :
1. None of my svgs have the a tag
2. They are not filled by default, only stroke'd but even if i add a fill,
I still get nothing,

Did you manage to get the svgs I attached to work on your end?

**Comment by shashi278** [comment]
I've modified your svgs. [Here](https://github.com/shashi278/svg-anim-kivy/files/7117492/img.zip)

**Comment by qodzero** [comment]
Thanks for these, they work now
